### your site title here

title: Alessandra Zinicola Lopez
description: Texts and Technology PhD Student | University of Central Florida | Made of All Work

baseurl: /AZLScholarlyWorkGradfolio #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "amadeofallwork"
linkedin: "azlopez"
github: "anonyzin"
orcid: "0000-0002-5333-742X"
instagram: "madeofallwork"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - Commerdingers.md
      - The1864PoeticalTable.md
      - ZinicolasJewelry.md
      - AmeliaSimmonsBot.md
      - ArchiveCookingGames.md
      - MangoesMelons.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
